// Code generated by templ - DO NOT EDIT.

// templ: version: v0.2.543
package vcomponent

//lint:file-ignore SA4006 This context is only used if a nested component is present.

import "github.com/a-h/templ"

import "alvintanoto.id/design-principle/internal/dto"

// TODO: simplify barchart function
func Chart(data []dto.ChartDataset, chartType string, target string) templ.ComponentScript {
	return templ.ComponentScript{
		Name: `__templ_Chart_925a`,
		Function: `function __templ_Chart_925a(data, chartType, target){new Chart(
    document.getElementById(target),
    {
      type: chartType,
      data: {
        labels: data.map(row => row.year),
        datasets: [
          {
            label: 'Acquisitions by year',
            data: data.map(row => row.count)
          }
        ]
      }
    }
  );
}`,
		Call:       templ.SafeScript(`__templ_Chart_925a`, data, chartType, target),
		CallInline: templ.SafeScriptInline(`__templ_Chart_925a`, data, chartType, target),
	}
}
