// Code generated by templ - DO NOT EDIT.

// templ: version: v0.2.543
package vcomponent

//lint:file-ignore SA4006 This context is only used if a nested component is present.

import "github.com/a-h/templ"

func LineChart() templ.ComponentScript {
	return templ.ComponentScript{
		Name: `__templ_LineChart_1f6a`,
		Function: `function __templ_LineChart_1f6a(){const data = [
    { year: 2010, count: 10 },
    { year: 2011, count: 20 },
    { year: 2012, count: 15 },
    { year: 2013, count: 25 },
    { year: 2014, count: 22 },
    { year: 2015, count: 30 },
    { year: 2016, count: 28 },
  ];

   new Chart(
    document.getElementById('linechart'),
    {
      type: 'line',
      data: {
        labels: data.map(row => row.year),
        datasets: [
          {
            label: 'Acquisitions by year',
            data: data.map(row => row.count)
          }
        ]
      }
    }
  );
}`,
		Call:       templ.SafeScript(`__templ_LineChart_1f6a`),
		CallInline: templ.SafeScriptInline(`__templ_LineChart_1f6a`),
	}
}

func Barchart() templ.ComponentScript {
	return templ.ComponentScript{
		Name: `__templ_Barchart_79ef`,
		Function: `function __templ_Barchart_79ef(){const data = [
    { year: 2010, count: 10 },
    { year: 2011, count: 20 },
    { year: 2012, count: 15 },
    { year: 2013, count: 25 },
    { year: 2014, count: 22 },
    { year: 2015, count: 30 },
    { year: 2016, count: 28 },
  ];

   new Chart(
    document.getElementById('barchart'),
    {
      type: 'bar',
      data: {
        labels: data.map(row => row.year),
        datasets: [
          {
            label: 'Acquisitions by year',
            data: data.map(row => row.count)
          }
        ]
      }
    }
  );
}`,
		Call:       templ.SafeScript(`__templ_Barchart_79ef`),
		CallInline: templ.SafeScriptInline(`__templ_Barchart_79ef`),
	}
}
